language: node_js

node_js:
  - "5.3"
  - "4.2"
  - "0.12"
  - "iojs"
  - "node"
  
addons:
  code_climate:
    repo_token: 025f6b2a60bb7e1a6cc99d6153144d9c611dc8aafc29084f7916ffdfc709582c

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  