language: node_js

node_js:
  - "node"
  - "6.4"
  - "5.3"
  - "4.5"
  - "iojs"
  - "0.12"
  
addons:
  code_climate:
    repo_token: 025f6b2a60bb7e1a6cc99d6153144d9c611dc8aafc29084f7916ffdfc709582c

after_script:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info

deploy:
  provider: npm
  email: vatev.1+npm@gmail.com
  api_key:
    secure: KzJ7bay3uMfnBhINLtPHeniOIurY1xCoRZ7/DNGla9c4zwSw21dM2otZMv02ygUhl/hd7fO0+HzH/BijjeW1YZSSQYrPSNtgr6mqc4m/P48aauTSLM4PE7lTHIdgDV9m6u8rJGAfqjKS7r9L71tCbtU738dwqAm4gJXJn57lBMn6ccyg1XOW+kAJob0/+eInMJzc5jpR9pxAyVmgAmjsL+rpcknKxWWE0+YIkGaT6gBitkeRE+7EGUXmP0nDb5Pn9oMXw3g+r5zbPcu/uQrKAwia2ZMc2zJyXrNMABpEh1E6v90BRGLLeDXaeRldLl8zNUEzWUqElIMm5C/NHr8S8lY39JLlWHbenBiRMxtWWckE+uOL1kB0O0ES/0P3L0H9NNXDoX8l8an1Ogqtr3bbscdNvjo7dQlDKJicWocjHWVIZAkNbAb8rOs8eQmdYXG9/TfxmJtKvplKzhInCJfd95Qi3KMeLru9oyd9YHiB49aVbhrRMSEsP0nC2ZB00+YqsHpCGuYNPolTTu6NRMzxLy7ciizyavdHSx+OFkkZzyuKWiiGEaxNb6mDl6HI6pdi0YUqxKTI6rxbGG1UrTBfkM3iChSlXZyIvFEXRH9+Nvs7cZvGl1WImMw0ej7FP6VAwjvHMhvLf/tuqqt0lEmgKyCtsM8AVAPxY/0mMPFcmww=
  on:
    tags: true
    repo: catdad/unstyle
